#!/bin/bash

HOME=$PWD

if [ "$1" == "" ]; then
	#compile everything
	echo "Compiling everything";
	cd $HOME/src/Enrollment;
	javac -d $HOME/bin/Enrollment *.java;
	cd $HOME/src/DataWriter;
	javac -d $HOME/bin/DataWriter *.java
elif [ "$1" == "e" ]; then
	#compile the main Enrollment code 
	echo "Compiling the Enrollment code";
	cd $HOME/src/Enrollment;
	javac -d $HOME/bin/Enrollment *.java
elif [ "$1" == "w" ]; then
	#compile the data writer code
	echo "Compiling the DataWriter code";
	cd $HOME/src/DataWriter;
	javac -d $HOME/bin/DataWriter *.java
else 
	echo "Couldn't understand argument, use \"\", \"e\", or \"w\"";
fi


