#!/bin/bash

HOME=$PWD

if [ "$1" == "e" ]; then
	#run the main Enrollment code 
	cd $HOME/bin/Enrollment;
	java Execute;
elif [ "$1" == "w" ]; then
	#run the data writer code
	cd $HOME/bin/DataWriter;
	java DataWriter;
else 
	echo "Couldn't understand argument, use \"e\" or \"w\""
fi
